---
name: "Automated Release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Build release"
    runs-on: "windows-latest"

    steps:
      - name: "List files"
        run: tree

      - name: "Build Anticheat"
        run: |
          ./.rojo/rojo.exe build --output Anticheat.rbxm

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Anticheat.rbxm