---
name: "Automated Release"

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: "Build release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      
      - name: "Build Anticheat"
        run: |
          "./.github/rojo" build --output Anticheat.rbxm
        shell: bash

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            Anticheat.rbxm